#### <center>Université de Toulouse  2025-2026, L3</center>

# Simulations stochastiques - TP3

Le but de ce TP est de résoudre l'exercice 1 du TD3 sur les chaînes de Markov. On définit dans le préambule la matrice de transition `P` et l'espace d'états $x=\{1,2,3\}$ qui sont des variables globales pour tout le TP (ne pas les modifier).

Toutes les simulations se feront avec `rand(...)` qui permet de simuler une ou plusieurs v.a. de loi uniforme sur $[0,1]$. On n'utilisera pas d'instructions pour d'autres lois.

Attention : la librairie numpy fournit des objets de type matrix et array qui diffèrent dans leurs usages. [Voir ces explications](https://stackoverflow.com/questions/4151128/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-u) par exemple.

In [5]:
%matplotlib inline
from matplotlib.pyplot import *
from math import *
from numpy import *
from numpy.random import *
from scipy.misc import *
from scipy.stats import *

P=array([[1./2, 1./4, 1./4], [0, 3./4, 1./4], [1./4, 1./4, 1./2]])
print("La matrice de transition : P")
print(P)
print("\nAccéder à la ligne 1 : P[1] ou P[1,:]")
print(P[1])
print(P[1,:])
print("\nL'espace d'états :  x")
x=[1,2,3]
print(x)
print("\nAfficher des proportions :  X=matrix([2,3,2,3,1]); print(float(sum(X==2))/ 5)")
X=matrix([2,3,2,3,1]); print(float(sum(X==2))/ 5); 

La matrice de transition : P
[[0.5  0.25 0.25]
 [0.   0.75 0.25]
 [0.25 0.25 0.5 ]]

Accéder à la ligne 1 : P[1] ou P[1,:]
[0.   0.75 0.25]
[0.   0.75 0.25]

L'espace d'états :  x
[1, 2, 3]

Afficher des proportions :  X=matrix([2,3,2,3,1]); print(float(sum(X==2))/ 5)
0.4


## Question 1
Définir une fonction qui, étant donnés un vecteur de probabilités $p$ de longueur $3$ et un entier $N \geq 1$, renvoie un tableau contenant $N$ simulations d'une variable aléatoire $X$ dans l'espace d'états $x=\{1,2,3\}$ avec la loi déterminée par $p$, c'est-à-dire telle que $P(X = x_i) = p_i$ pour tout $i \in \{1,2,3\}$. Vérifier votre simulation sur un exemple bien choisi.

In [ ]:
def simuDiscrete(p,N):
    X=zeros(N)
    
    return(X)

## Question 2
Etant donné un vecteur de probabilités $p$ de taille $3$ et un entier $n \geq 1$, simuler les $n$ premiers états $(X_k)_{k = 1, 2, \ldots n}$  de la chaîne de Markov de l'exercice 1 du TD3 avec $X_1 \sim p$. Autrement dit, on veut que $P(X_1 = i) = p_i$ pour tout $i=1,2,3$, et, pour tous $k = 1,2,\ldots,n-1$ et $i,j = 1,2,3$,
$$P\big(X_{k+1} = j \, \big| \, X_k = i\big) = p_{i,j}$$ 
où les $p_{i,j}$ correspondent aux coefficients de la matrice `P` définie en préambule. Vérifiez bien votre code : la fonction **`simuMarkov` servira dans toute la suite**.

In [ ]:
def simuMarkov(p,n):
    X=zeros(n)
    
    return X

## Question 3
TD3, Ex 1, Q5 : Supposons que la loi de $X_1$ est donnée par $\mu$. Quelle est alors la loi de $X_2$ ? Réaliser 10000 simulations de $X_2$ et vérifier votre observation. 

Indice : dans ce cas, la loi de $X_2$ est $\mu$ car $\mu$ est la mesure invariante de la chaîne. On rappelle que $\mu = \left(\frac{1}{6},\frac{1}{2}, \frac{1}{3}\right)$.

In [ ]:
N=10**4
X2 = zeros(N)
mu=[1./6, 1./2, 1./3]



## Question 4
TD3, Ex 1, Q4 : supposons que $P(X_1 = 1) = 1$. Quelle est la loi de $X_4$ ? Calculer numériquement cette loi et réaliser 10000 simulations de $X_4$. Vérifier empiriquement que $X_4$ suit la loi attendue.

Indice : La loi de $X_4$ est donnée par $(1,0,0) \times P^3$. $P$ est un tableau, calculer $P^k$ s'écrit `matrix(P)**k`. Le vecteur horizontal $(1,0,0)$ s'écrit `matrix([1,0,0])`.


In [ ]:
N=10**4
X4 = zeros(N)



## Question 5
TD3, Ex 1, Q6 : Supposons que $P(X_1 = 1) = 1$. Sous cette condition, réaliser $M = 1000$ simulations de $(X_{k})_{k=1,2\ldots,15}$. A partir de cette simulation, estimer $P(X_{k} = i)$ pour $i = 1,2,3$ et $k = 1,2,\ldots,15$. Dessiner et comparer le résultat à la mesure invariante $\mu$. Quel résultat du cours est illustré ici ?

In [7]:
M=1000
n=15
XX = zeros((M,n))

## Question 6
TD3, Ex 1, Q7 : Supposons que $P(X_1 = 1) = 1$. Sous cette condition, réaliser **une** simulation des $10000$ premières variables $(X_k)_{1 \leq k \leq 10000}$ de la chaîne. Tracer ensuite un histogramme donnant la proportion du nombre d'instants où la chaîne est située en chacun des états $1$, $2$ et $3$. Comparer le résultat à la mesure invariante $\mu$. Essayer de faire un lien avec la question précédente.


## Question 7 (pour aller plus loin)
TD3, Ex 1, Q8 : la librairie `numpy.linalg` contient des fonctions d'algèbre linéaire ; utilisez les pour retrouver numériquement la mesure invariante $\mu$.

# Exercice supplémentaire pour vous entraîner
Soit $(X_n)_{n \geq 1}$ une chaîne de Markov sur l'espace
$\{1,2,3\}$, telle que $P(X_1 = 1) = 1$ et
dont la matrice de transition est donnée par 
$$ Q= \left( \begin{array}{ccc} 0.8 & 0.2 & 0 \\ 0.1 & 0.8 & 0.1 \\ 0 & 0.2 & 0.8 \end{array} \right).$$

a) Ecrire une fonction permettant de simuler une réalisation des $n$ premiers pas de la chaîne.

b) Quelle est la loi de $X_3$? Vérifiez le résultat par un histogramme.

c) Vérifiez que $(1/4,1/2,1/4)$ est une loi de probabilités invariante pour $Q$. Réalisez $M = 200$ simulations de $X_{1000}$ et estimez $P(X_{1000} = i)$ pour $i = 1,2,3$. Dessiner et comparer le résultat à la mesure invariante.

d) Réalisez **une** simulation des $10000$ premières variables $(X_k)_{1 \leq k \leq 10000}$ de la chaîne. Tracer ensuite un histogramme donnant la proportion du nombre d'instants où la chaîne est située en chacun des états $1$, $2$ et $3$. Comparer le résultat à la mesure invariante.